<?php
/**
 * Example configuration generated by install.php.
 * Copying this file is optional; production installs should use install.php so
 * credentials are validated before config.php is written.
 */
if (isset($_SERVER['SCRIPT_FILENAME']) && realpath($_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    http_response_code(403);
    exit('Forbidden');
}

return [
    'app' => [
        'environment' => 'production',
        'debug' => false,
        'base_url' => '',
        'timezone' => 'Asia/Tehran',
        'max_file_size' => 5 * 1024 * 1024,
    ],
    'db' => [
        'host' => '',
        'name' => '',
        'user' => '',
        'pass' => '',
        'charset' => 'utf8mb4',
    ],
];
