-- Phase 7 organizational tests and business standard assessments.
-- Additive only. hr_assessment_tests remains the canonical test bank.

CREATE TABLE IF NOT EXISTS `hr_assessment_tests` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar(180) NOT NULL,
  `test_code` varchar(80) NOT NULL,
  `category` varchar(80) NOT NULL DEFAULT 'organizational_behavior',
  `question_count` int(11) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `scoring_method_type` varchar(40) NOT NULL DEFAULT 'calculated',
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `intended_use` varchar(180) DEFAULT NULL,
  `time_limit_minutes` int(11) DEFAULT NULL,
  `assigned_role` varchar(60) DEFAULT NULL,
  `assigned_department` varchar(100) DEFAULT NULL,
  `allow_retake` tinyint(1) NOT NULL DEFAULT 1,
  `retake_policy` enum('free','manager_approval_required') NOT NULL DEFAULT 'manager_approval_required',
  `show_disclaimer` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  `updated_by` int(11) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_assessment_test_code_phase7` (`test_code`),
  KEY `idx_hr_assessment_active_order_phase7` (`is_active`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_dimensions` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `test_id` int(11) UNSIGNED NOT NULL,
  `code` varchar(80) NOT NULL,
  `title` varchar(180) NOT NULL,
  `description` text DEFAULT NULL,
  `positive_label` varchar(120) DEFAULT NULL,
  `negative_label` varchar(120) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  `updated_by` int(11) UNSIGNED DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_test_dimension_phase7` (`test_id`, `code`),
  KEY `idx_hr_test_dimension_test_phase7` (`test_id`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_questions` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `test_id` int(11) UNSIGNED NOT NULL,
  `dimension_id` int(11) UNSIGNED DEFAULT NULL,
  `code` varchar(80) NOT NULL,
  `question_text` text NOT NULL,
  `answer_type` varchar(40) NOT NULL DEFAULT 'single_choice',
  `question_type` varchar(40) DEFAULT NULL,
  `options_json` longtext DEFAULT NULL,
  `weight` decimal(7,2) NOT NULL DEFAULT 1.00,
  `scoring_direction` varchar(20) NOT NULL DEFAULT 'positive',
  `score_direction` varchar(20) DEFAULT NULL,
  `is_reverse_scored` tinyint(1) NOT NULL DEFAULT 0,
  `is_required` tinyint(1) NOT NULL DEFAULT 1,
  `is_critical` tinyint(1) NOT NULL DEFAULT 0,
  `role_visibility` varchar(500) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  `updated_by` int(11) UNSIGNED DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_test_question_phase7` (`test_id`, `code`),
  KEY `idx_hr_test_question_test_phase7` (`test_id`, `is_active`, `sort_order`),
  KEY `idx_hr_test_question_dimension_phase7` (`dimension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_options` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` int(11) UNSIGNED NOT NULL,
  `title` varchar(500) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `score_value` decimal(8,2) NOT NULL DEFAULT 0.00,
  `dimension_code` varchar(80) DEFAULT NULL,
  `is_correct` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  `updated_by` int(11) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_test_option_phase7` (`question_id`, `slug`),
  KEY `idx_hr_test_option_question_phase7` (`question_id`, `status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_scoring_rules` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `test_id` int(11) UNSIGNED NOT NULL,
  `title` varchar(180) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `rule_type` varchar(60) NOT NULL DEFAULT 'positive',
  `rule_config_json` longtext DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_by` int(11) UNSIGNED DEFAULT NULL,
  `updated_by` int(11) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_test_scoring_rule_phase7` (`test_id`, `slug`),
  KEY `idx_hr_test_scoring_test_phase7` (`test_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_assignments` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `test_id` int(11) UNSIGNED NOT NULL,
  `target_type` varchar(40) NOT NULL DEFAULT 'employee',
  `target_id` varchar(120) DEFAULT NULL,
  `employee_id` int(11) UNSIGNED DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `role` varchar(60) DEFAULT NULL,
  `period_id` int(11) UNSIGNED DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `status` varchar(40) NOT NULL DEFAULT 'active',
  `allow_retake` tinyint(1) NOT NULL DEFAULT 1,
  `max_attempts` int(11) UNSIGNED NOT NULL DEFAULT 1,
  `show_result_to_employee` tinyint(1) NOT NULL DEFAULT 1,
  `description` text DEFAULT NULL,
  `assigned_by` int(11) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hr_test_assignment_test_phase7` (`test_id`, `status`),
  KEY `idx_hr_test_assignment_employee_phase7` (`employee_id`, `status`),
  KEY `idx_hr_test_assignment_scope_phase7` (`target_type`, `target_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_attempts` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) UNSIGNED NOT NULL,
  `test_id` int(11) UNSIGNED NOT NULL,
  `employee_id` int(11) UNSIGNED NOT NULL,
  `attempt_no` int(11) UNSIGNED NOT NULL DEFAULT 1,
  `status` varchar(30) NOT NULL DEFAULT 'in_progress',
  `started_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_test_attempt_no_phase7` (`assignment_id`, `employee_id`, `attempt_no`),
  KEY `idx_hr_test_attempt_employee_phase7` (`employee_id`, `status`),
  KEY `idx_hr_test_attempt_test_phase7` (`test_id`, `submitted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_responses` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) UNSIGNED DEFAULT NULL,
  `attempt_id` int(11) UNSIGNED DEFAULT NULL,
  `test_id` int(11) UNSIGNED NOT NULL,
  `employee_id` int(11) UNSIGNED NOT NULL,
  `period_id` int(11) UNSIGNED DEFAULT NULL,
  `status` varchar(40) NOT NULL DEFAULT 'in_progress',
  `answers_json` longtext DEFAULT NULL,
  `dimension_scores_json` longtext DEFAULT NULL,
  `profile_output` varchar(180) DEFAULT NULL,
  `normalized_score` decimal(6,2) DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hr_test_response_employee_phase7` (`employee_id`, `status`),
  KEY `idx_hr_test_response_test_phase7` (`test_id`, `submitted_at`),
  KEY `idx_hr_test_response_assignment_phase7` (`assignment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_results` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `attempt_id` int(11) UNSIGNED DEFAULT NULL,
  `assignment_id` int(11) UNSIGNED DEFAULT NULL,
  `test_id` int(11) UNSIGNED NOT NULL,
  `employee_id` int(11) UNSIGNED NOT NULL,
  `overall_score` decimal(6,2) DEFAULT NULL,
  `result_level` varchar(120) DEFAULT NULL,
  `profile_code` varchar(120) DEFAULT NULL,
  `dimension_scores_json` longtext DEFAULT NULL,
  `strengths_json` longtext DEFAULT NULL,
  `improvements_json` longtext DEFAULT NULL,
  `recommendations_json` longtext DEFAULT NULL,
  `warnings_json` longtext DEFAULT NULL,
  `analysis_disclaimer` varchar(500) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'final',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_hr_test_result_attempt_phase7` (`attempt_id`),
  KEY `idx_hr_test_result_employee_phase7` (`employee_id`, `created_at`),
  KEY `idx_hr_test_result_test_phase7` (`test_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_retake_requests` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `assignment_id` int(11) UNSIGNED NOT NULL,
  `test_id` int(11) UNSIGNED NOT NULL,
  `employee_id` int(11) UNSIGNED NOT NULL,
  `request_note` text DEFAULT NULL,
  `status` enum('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
  `reviewed_by` int(11) UNSIGNED DEFAULT NULL,
  `review_note` text DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_test_retake_assignment_phase7` (`assignment_id`, `employee_id`, `status`),
  KEY `idx_hr_test_retake_test_phase7` (`test_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `hr_test_audit_logs` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `actor_id` int(11) UNSIGNED DEFAULT NULL,
  `action` varchar(80) NOT NULL,
  `entity_type` varchar(80) NOT NULL,
  `entity_id` int(11) UNSIGNED DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `context_json` longtext DEFAULT NULL,
  `ip_hash` char(64) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_test_audit_entity_phase7` (`entity_type`, `entity_id`, `created_at`),
  KEY `idx_hr_test_audit_actor_phase7` (`actor_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
